### ISSUE TITLE
Add support for IDS other than `core_profiles`

### ISSUE THREAD

**Issue by aaronkho** [CarbonCollective/fusion-dUQtools#225]
Currently there is only support for `core_profiles`, which is hard-coded in several places. Duqtools should be updated to add support for other IDS as well, such as `core_sources`, `pulse_schedule` and `equilibrium`.

<details>
  <summary>Click for old comment</summary>

I've pulled the latest `main` branch commit, 9135f5d1, and generated my old .yaml file:
```
create:
  data:
    db: jet97781_current_diffusion
    run_in_start_at: 1000
    run_out_start_at: 1100
  dimensions:
  - ids: pulse_schedule/tf/b_field_tor_vacuum_r/data
    operator: add
    scale_to_error: true
    values: [-2, -1, 0, 1, 2]
  - ids: pulse_schedule/flux_control/
    operator: add
    scale_to_error: true
    values: [-2, -1, 0, 1, 2]
  - ids: profiles_1d/0/electrons/temperature
    operator: add
    scale_to_error: true
    values: [-2, -1, 0, 1, 2]
  - ids: profiles_1d/0/electrons/density
    operator: add
    scale_to_error: true
    values: [-2, -1, 0, 1, 2]
  sampler:
    method: latin-hypercube
    n_samples: 20
  template: /pfs/work/g2aho/jetto/runs/rundt_analysis/jet97781/current_diff01_qlknnmod/
workspace:
  root: /pfs/work/g2aho/jetto/runs/
```

I get the following error while running the `create` command:
```
Do you want to apply all these operations? [y/N]: y
Create folder : /gss_efgw_work/work/g2aho/jetto/runs/rundt_analysis/jet97781/duqCreate folder : /gss_efgw_work/work/g2aho/jetto/runs/rundt_analysis/jet97781/duqtest/run_0000:
Applying operations:   1%|▏                     | 1/121 [00:00<01:23,  1.43it/s]
Traceback (most recent call last):
  File "/afs/eufus.eu/user/g/g2aho/.local/bin/duqtools", line 33, in <module>
    sys.exit(load_entry_point('duqtools', 'console_scripts', 'duqtools')())
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/cli.py", line 159, in cli_create
    with op_queue_context():
  File "/gw/switm/python/3.10.2/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/operations.py", line 300, in op_queue_context
    op_queue.confirm_apply_all()
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/operations.py", line 186, in confirm_apply_all
    self.apply_all()
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/operations.py", line 157, in apply_all
    op()
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/operations.py", line 78, in __call__
    self.action(*self.args, **self.kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/ids/_copy.py", line 140, in copy_ids_entry
    ids.get(i)
  File "/gw/swimas/core/IMAS/3.36.0/AL/4.10.2/python/lib.linux-x86_64-3.10/imas_3_36_0_ual_4_10_2/amns_data.py", line 151, in get
    homogeneousTime = self.readHomogeneous(db_ctx, occurrence)
  File "/gw/swimas/core/IMAS/3.36.0/AL/4.10.2/python/lib.linux-x86_64-3.10/imas_3_36_0_ual_4_10_2/ids_base.py", line 102, in readHomogeneous
    raise ALException('Error calling ual_begin_global_action() in readHomogeneous() operation', status)
imas_3_36_0_ual_4_10_2.hli_exception.ALException: Error calling ual_begin_global_action() in readHomogeneous() operation
Error status=-4
There are unconfirmed operations in the queue at program exit!

...
Did you forget to use the @confirm_operations decorator?
```
</details>

**Comment by v1kko** [comment]
Rename db to imasdb

**Comment by v1kko** [comment]
the pulse data fields give an error

**Comment by aaronkho** [comment]
Corrected .yaml to have `db: jet`. Now returns error:
```
Traceback (most recent call last):
  File "/afs/eufus.eu/user/g/g2aho/.local/bin/duqtools", line 33, in <module>
    sys.exit(load_entry_point('duqtools', 'console_scripts', 'duqtools')())
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/cor
e.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/cor
e.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/cor
e.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/cor
e.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/cor
e.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/
cli.py", line 159, in cli_create
    with op_queue_context():
  File "/gw/switm/python/3.10.2/lib/python3.10/contextlib.py", line 142, in __ex
it__
    next(self.gen)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/
operations.py", line 300, in op_queue_context
    op_queue.confirm_apply_all()
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/
operations.py", line 186, in confirm_apply_all
    self.apply_all()
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/
operations.py", line 157, in apply_all
    op()
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/
operations.py", line 78, in __call__
    self.action(*self.args, **self.kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/
create.py", line 36, in apply_combination
    apply_model(model, ids_mapping)
  File "/gw/switm/python/3.10.2/lib/python3.10/functools.py", line 889, in wrapp
er
    return dispatch(args[0].__class__)(*args, **kw)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/
ids/_dimensions.py", line 40, in _
    profile = ids_mapping[model.ids]
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/
ids/_mapping.py", line 82, in __getitem__
    raise KeyError(key)
KeyError: 'pulse_schedule/tf/b_field_tor_vacuum_r/data'
```

**Comment by aaronkho** [comment]
It would be useful to extend data beyond core_profiles IDS as JETTO reads inputs from other IDSs as well, e.g. core_sources, pulse_schedule and equilibrium.

**Comment by stefsmeets** [comment]
@aaronkho I updated the config parser so that the tool also works with other IDS in #238 

I tested your script, and it works fine now. Since we changed the schema, this will cause a little bit of breakage with your scripts. This is what I had to change:

Note that I don't have error bars on the `pulse_schedule` values in the data that I use, so I turned the error scaling off.

```yaml
...
  dimensions:
    - ids: pulse_schedule
      path: tf/b_field_tor_vacuum_r/reference/data
      operator: add
      scale_to_error: false
      values: [-2, -1, 0, 1, 2]
    - ids: pulse_schedule
      path: flux_control/i_plasma/reference/data
      operator: add
      scale_to_error: false
      values: [-2, -1, 0, 1, 2]
    - ids: core_profiles
      path: profiles_1d/0/zeff
      operator: add
      values: [0.01, 0.02, 0.03]
    - ids: core_profiles
      path: profiles_1d/0/t_i_average
      operator: multiply
      values: [1.1, 1.2, 1.3]
...
```

I also updated `db` -> `imasdb` in the data section, so now you have to write:

```yaml
  data:
    imasdb: jet
    run_in_start_at: 7200
    run_out_start_at: 8200
```

I hope that is clearer! I'm going to close this for now, but please re-open this issue or a new one if you run into something else.
