### ISSUE TITLE
Error running status command

### ISSUE THREAD

**Issue by aaronkho** [CarbonCollective/fusion-dUQtools#226]
Running the `duqtools status --detailed` command too quickly after submission step yields the following error:

```
Traceback (most recent call last):                                                                                                                                                                                  | 0/100 [00:00<?, ?it/s]
  File "/afs/eufus.eu/user/g/g2aho/.local/bin/duqtools", line 33, in <module>
    sys.exit(load_entry_point('duqtools', 'console_scripts', 'duqtools')())
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/cli.py", line 180, in cli_status
    status(**kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/status.py", line 227, in status
    tracker.detailed_status()
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/status.py", line 134, in detailed_status
    monitor = Monitor(pbar=pbar, dir=dir)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/status.py", line 152, in __init__
    self.set_status()
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/status.py", line 169, in set_status
    elif is_running(self.dir):
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/status.py", line 43, in is_running
    return status_file_contains(dir, cfg.status.msg_running)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/status.py", line 27, in status_file_contains
    with open(sf, 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'run_0001/jetto.status'
```

I am not sure if this would propagate into large-scale UQ batches, where only a fraction of total runs are in the queue at any given moment.

**Comment by aaronkho** [comment]
This also crashes the program, so no information is provided on any runs with an index after the offending run index.
