### ISSUE TITLE
Sigma operations not working properly

### ISSUE THREAD

**Issue by aaronkho** [CarbonCollective/fusion-dUQtools#247]
I am using this `duqtools.yaml` file:
```
create:
  data:
    imasdb: jet
    run_in_start_at: 1000
    run_out_start_at: 2000
  dimensions:
  - ids: pulse_schedule
    operator: add
    path: tf/b_field_tor_vacuum_r/reference/data
    scale_to_error: true
    values: [-2, -1, 0, 1, 2]
  - ids: pulse_schedule
    operator: add
    path: flux_control/i_plasma/reference/data
    scale_to_error: true
    values: [-2, -1, 0, 1, 2]
  - ids: core_profiles
    operator: add
    path: profiles_1d/$i/t_i_average
    scale_to_error: true
    values: [-2, -1, 0, 1, 2]
  - ids: core_profiles
    operator: add
    path: profiles_1d/$i/electrons/temperature
    scale_to_error: true
    values: [-2, -1, 0, 1, 2]
  - ids: core_profiles
    operator: add
    path: profiles_1d/$i/electrons/density
    scale_to_error: true
    values: [-2, -1, 0, 1, 2]
  sampler:
    method: latin-hypercube
    n_samples: 21
  template: /pfs/work/g2aho/jetto/runs/rundt_analysis/jet97781/current_diff01_qlknnmod/
workspace:
  root: /pfs/work/g2aho/jetto/runs/
```

And receiving this error:
```
Traceback (most recent call last):
  File "/afs/eufus.eu/user/g/g2aho/.local/bin/duqtools", line 8, in <module>
    sys.exit(cli())
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/afs/eufus.eu/user/g/g2aho/.local/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/cli.py", line 161, in cli_create
    with op_queue_context():
  File "/gw/switm/python/3.10.2/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/operations.py", line 304, in op_queue_context
    op_queue.confirm_apply_all()
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/operations.py", line 190, in confirm_apply_all
    self.apply_all()
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/operations.py", line 163, in apply_all
    op()
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/operations.py", line 80, in __call__
    self.action(*self.args, **self.kwargs)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/create.py", line 37, in apply_combination
    apply_model(model, ids_mapping)
  File "/gw/switm/python/3.10.2/lib/python3.10/functools.py", line 889, in wrapper
    return dispatch(args[0].__class__)(*args, **kw)
  File "/afs/eufus.eu/g2itmuse/user/g2aho/gitrepos/fusion-dUQtools/src/duqtools/ids/_dimensions.py", line 53, in _
    sigma = abs(sigma_bound - data)
ValueError: operands could not be broadcast together with shapes (0,) (101,)
```

I have already checked that the input IDS of the template run (`g2aho/jet/97781/1`) contains all the necessary data and error fields.

**Comment by stefsmeets** [comment]
Thanks for the report! Judging by the error, my first guess would be that one of your variables does not have error bars (`..._error_upper`). But maybe it is something else if you say that all these have error bars. I wil check this on Monday 👍

**Comment by stefsmeets** [comment]
Hi @aaronkho , I'm unable to read these data, I get:

```
Exception: ('Error while reading data:', b'ual_read_data: [UALBackendException = Internal error: array of structure is not an APD data]')
```

I think I understand the problem though, I will submit a fix once I find the right way to solve it 👍

**Comment by stefsmeets** [comment]
Hi @aaronkho I think I fixed the issue in #248. I already merged it to main. I couldn't verify whether it works with your data, so could you please check if this fixes it for you and let me know if it doesn't?

**Comment by aaronkho** [comment]
@stefsmeets I have checked it with my data and it appears to work properly. However, I am noticing another issue with improper ranges. The sigma values around `rho_tor_norm = 1` are often larger than the mean value. This means the simple error operation can result in negative temperatures and densities if done blindly. I believe JINTRAC will crash when given inputs of this nature but I have to double-check this.

Are there user-definable fields in the `duqtools.yaml` file to specify upper / lower limits for the applied operation? If not, can something like this be added?

**Comment by stefsmeets** [comment]
Glad to hear it works better now!

Setting lower or upper limits on these ranges is not something that I think we will have in duqtools. I think this should be fixed in the data instead. If the error bar overlaps with what is physically possible, then to me it makes sense to fix it there instead. I guess this could be done by mirroring `*_error_upper` around the mean to get `*error_lower` and setting it to 0 where it it goes negative.

Since the issue in the OP is fixed, I'm going to close this issue. Feel free to open a new issue if bounds on the error bound sampling is something worth adding to duqtools.
