### ISSUE TITLE
Error when trying to create a new db

### ISSUE THREAD

**Issue by stefsmeets** [CarbonCollective/fusion-dUQtools#64]
When trying to write IDS data to a new entry with a db/machine name that does not yet exist, the program crashes with this error message:

```pycon
ERROR:root:b'ual_open_pulse: [UALBackendException = %TREE-E-FOPENR, Error opening file read-only.]'
ERROR:root:b'ual_open_pulse: [UALBackendException = %TREE-E-FCREATE, Error creating new file.]'
Traceback (most recent call last):
  File "/afs/eufus.eu/g2itmuse/user/g2ssmee/duqtools/venv/bin/duqtools", line 33, in <module>
    sys.exit(load_entry_point('duqtools', 'console_scripts', 'duqtools')())
  File "/afs/eufus.eu/g2itmuse/user/g2ssmee/duqtools/duqtools/__main__.py", line 73, in cmdline
    args.func(args=args)
  File "/afs/eufus.eu/g2itmuse/user/g2ssmee/duqtools/duqtools/create.py", line 88, in create
    core_profiles = target_in.get('core_profiles')
  File "/afs/eufus.eu/g2itmuse/user/g2ssmee/duqtools/duqtools/ids/ids_location.py", line 90, in get
    data = data_entry.get(key)
  File "/gw/swimas/core/IMAS/3.34.0/AL/4.9.3/python/lib.linux-x86_64-3.7/imas_3_34_0_ual_4_9_3/db_entry.py", line 85, in get
    ids.get(occurrence, self)
  File "/gw/swimas/core/IMAS/3.34.0/AL/4.9.3/python/lib.linux-x86_64-3.7/imas_3_34_0_ual_4_9_3/core_profiles.py", line 110, in get
    homogeneousTime = self.readHomogeneous(db_ctx, occurrence)
  File "/gw/swimas/core/IMAS/3.34.0/AL/4.9.3/python/lib.linux-x86_64-3.7/imas_3_34_0_ual_4_9_3/ids_base.py", line 104, in readHomogeneous
    status, homogeneousTime = ull.ual_read_data(ctx, "ids_properties/homogeneous_time", "", INTEGER_DATA, 0)
  File "imas_3_34_0_ual_4_9_3/_ual_lowlevel.pyx", line 851, in imas_3_34_0_ual_4_9_3._ual_lowlevel.ual_read_data
  File "imas_3_34_0_ual_4_9_3/_ual_lowlevel.pyx", line 699, in imas_3_34_0_ual_4_9_3._ual_lowlevel.ual_read_data_scalar
Exception: ('Error while reading data:', b'ual_read_data: [UALBackendException = Pulse file not open]')
```

This script will reproduce the error (with a new target db location that does not yet exist):

```python
from duqtools.ids.ids_location import ImasLocation

source = ImasLocation(db='jet', shot=92432, user='g2aho', run=1)
target = ImasLocation(db='non-existant-db', shot=source.shot, run=1001)

source.copy_ids_entry_to(target)
core_profiles = target.get('core_profiles')

with target.open() as data_entry_target:
    core_profiles.put(db_entry=data_entry_target)
```

**Comment by aaronkho** [comment]
With the installation of the IMAS infrastructure comes a console command `imasdb <machine_name>`, which creates the db/machine name directory in the default IMASDB directory. I do not know of any way to access this API directly, but maybe you can put `subprocess.run(["imasdb", db])` in the script if the db does not exist yet?

**Comment by stefsmeets** [comment]
Thanks! I just checked the documentaiton, and there seems to be no interface for doing this via the API, so that is a good suggestion.
